version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pwd
      MYSQL_DATABASE: LibraryBookManagementSystem
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  java-app:
    build: .
    container_name: java-app-container
    ports:
      - "9000:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/LibraryBookManagementSystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pwd
    networks:
      - app-network
volumes:
  mysql-data:
networks:
  app-network:
    driver: bridge

